In [17]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from bs4 import BeautifulSoup
import time

# Cấu hình Chrome
options = Options()

# Giả lập trình duyệt thông thường
options.add_argument("--start-maximized")

# Khởi tạo Chrome
driver = webdriver.Chrome(options=options)

try:
    url = "https://www.cgv.vn/"
    driver.get(url)

    # Chờ trang tải
    time.sleep(5)

    print("Tiêu đề:", driver.title)
    print("URL:", driver.current_url)

    # Lấy HTML
    html = driver.page_source

    print("Độ dài HTML:", len(html))

finally:
    driver.quit()

Tiêu đề: CGV Cinemas Vietnam | Thông tin - Lịch chiếu - Hệ thống rạp chiếu phim đẳng cấp CGV Cinemas Việt Nam
URL: https://www.cgv.vn/
Độ dài HTML: 126693

In [18]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from bs4 import BeautifulSoup
import pandas as pd
import time
from urllib.parse import urljoin

BASE_URL = "https://www.cgv.vn"

options = Options()
options.add_argument("--start-maximized")

driver = webdriver.Chrome(options=options)

try:
    driver.get(BASE_URL)

    time.sleep(5)

    soup = BeautifulSoup(driver.page_source, "html.parser")

    movies = soup.select("li.poster-film")

    print("Số phim:", len(movies))

    data = []

    for movie in movies:

        img = movie.select_one("img.product-img")
        rating = movie.select_one(".movie-rating")
        detail_link = movie.select_one('a[title="Xem chi tiết"]')

        movie_name = img.get("alt") if img else None

        image_url = img.get("src") if img else None

        movie_rating = (
            rating.get_text(strip=True)
            if rating else None
        )

        movie_url = (
            urljoin(BASE_URL, detail_link.get("href"))
            if detail_link else None
        )

        data.append({
            "MovieName": movie_name,
            "MovieURL": movie_url,
            "ImageURL": image_url,
            "Rating": movie_rating
        })

    df = pd.DataFrame(data)

    print(df)

    df.to_csv(
        "cgv_movies.csv",
        index=False,
        encoding="utf-8-sig"
    )

finally:
    driver.quit()

Số phim: 29
                                            MovieName  \
0   AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT (CHIẾU ...
1   AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT (CHIẾU ...
2                                     TRẠI BUÔN NGƯỜI
3                                   HÒN ĐẢO QUÊN LÃNG
4                                           LÊN HƯƠNG
5                                            ÚT LAN 2
6                                     VÙNG ĐẤT QUỶ DỮ
7                                      MARNIE YÊU DẤU
8                                     BÓNG MA NHÀ HÁT
9                                     TẾ NHI CẢI MỆNH
10                YÊU NHÂN THẦN THÁM: KỲ ÁN TRƯỜNG AN
11                                NGHỈ HÈ SỢ NGHỈ HƯU
12                                   HOPE VÙNG TỬ ĐỊA
13                                   QUÝ TỬ VƯỢT GIÀU
14                            MÃI NỢ MỘT LỜI TẠM BIỆT
15                                  CỔ THUẬT HẮC NGẢI
16                            BÙA YÊU: BÍ MẬT GIA TỘC
17                     CHIIKAWA: BÍ MẬT ĐẢO NGƯỜI CÁ
18                    BÁT TIÊN ! TRUY TÌM LƯU LY ĐĂNG
19     HỘ LINH TRÁNG SĨ - Bí Ẩn Mộ Vua Đinh (RÚT GỌN)
20                                              MA TÙ
21                                   MỘT ĐÊM DUY NHẤT
22  PHIM SHIN – CẬU BÉ BÚT CHÌ: KỲ KỲ QUÁI QUÁI! K...
23                                    TÀU BUÔN NGƯỜI
24                       QUỶ QUYỆT: RANH GIỚI VÔ ĐỊNH
25                        PAW PATROL: PHIM KHỦNG LONG
26                           NGƯỜI NHỆN: KHỞI ĐẦU MỚI
27                                        THE ODYSSEY
28                     KHÔNG CÒN CHÚNG TA (CHIẾU LẠI)

                                             MovieURL  \
0   https://www.cgv.vn/default/avengers-endgame-en...
1   https://www.cgv.vn/default/avengers-endgame-en...
2     https://www.cgv.vn/default/trai-buon-nguoi.html
3    https://www.cgv.vn/default/forgotten-island.html
4           https://www.cgv.vn/default/len-huong.html
5            https://www.cgv.vn/default/ut-lan-2.html
6   https://www.cgv.vn/default/resident-evil-2026....
7      https://www.cgv.vn/default/marnie-yeu-dau.html
8     https://www.cgv.vn/default/bong-ma-nha-hat.html
9        https://www.cgv.vn/default/tao-exorcist.html
10        https://www.cgv.vn/default/demon-agent.html
11  https://www.cgv.vn/default/nghi-he-so-nghi-huu...
12               https://www.cgv.vn/default/hope.html
13   https://www.cgv.vn/default/quy-tu-vuot-giau.html
14          https://www.cgv.vn/default/chrysalis.html
15           https://www.cgv.vn/default/kong-tao.html
16  https://www.cgv.vn/default/bua-yeu-bi-mat-gia-...
17  https://www.cgv.vn/default/chiikawa-the-movie....
18           https://www.cgv.vn/default/bat-tien.html
19  https://www.cgv.vn/default/ho-linh-trang-si-ru...
20              https://www.cgv.vn/default/ma-tu.html
21     https://www.cgv.vn/default/one-night-only.html
22  https://www.cgv.vn/default/shin-yokai-vacation...
23             https://www.cgv.vn/default/mutiny.html
24  https://www.cgv.vn/default/insidious-further.html
25    https://www.cgv.vn/default/paw-patrol-dino.html
26  https://www.cgv.vn/default/spider-brand-new-da...
27        https://www.cgv.vn/default/the-odyssey.html
28    https://www.cgv.vn/default/once-we-were-us.html

                                             ImageURL Rating
0   https://static-cgv.vncdn.vn/media/catalog/prod...   None
1   https://static-cgv.vncdn.vn/media/catalog/prod...   None
2   https://static-cgv.vncdn.vn/media/catalog/prod...   None
3   https://static-cgv.vncdn.vn/media/catalog/prod...   None
4   https://static-cgv.vncdn.vn/media/catalog/prod...   None
5   https://static-cgv.vncdn.vn/media/catalog/prod...   None
6   https://static-cgv.vncdn.vn/media/catalog/prod...   None
7   https://static-cgv.vncdn.vn/media/catalog/prod...   None
8   https://static-cgv.vncdn.vn/media/catalog/prod...   None
9   https://static-cgv.vncdn.vn/media/catalog/prod...   None
10  https://static-cgv.vncdn.vn/media/catalog/prod...   None
11  https://static-cgv.vncdn.vn/media/catalog/prod...   None
12  https://static-cgv.vncdn.vn/media/catalog/prod...   None
13  https://static-cgv.vncdn.vn/media/catalog/prod...   None
14  https://static-cgv.vncdn.vn/media/catalog/prod...   None
15  https://static-cgv.vncdn.vn/media/catalog/prod...   None
16  https://static-cgv.vncdn.vn/media/catalog/prod...   None
17  https://static-cgv.vncdn.vn/media/catalog/prod...   None
18  https://static-cgv.vncdn.vn/media/catalog/prod...   None
19  https://static-cgv.vncdn.vn/media/catalog/prod...   None
20  https://static-cgv.vncdn.vn/media/catalog/prod...   None
21  https://static-cgv.vncdn.vn/media/catalog/prod...   None
22  https://static-cgv.vncdn.vn/media/catalog/prod...   None
23  https://static-cgv.vncdn.vn/media/catalog/prod...   None
24  https://static-cgv.vncdn.vn/media/catalog/prod...   None
25  https://static-cgv.vncdn.vn/media/catalog/prod...   None
26  https://static-cgv.vncdn.vn/media/catalog/prod...   None
27  https://static-cgv.vncdn.vn/media/catalog/prod...   None
28  https://static-cgv.vncdn.vn/media/catalog/prod...   None

In [22]:
from selenium import webdriver
import time

driver = webdriver.Chrome()

driver.get("https://www.cgv.vn/")

time.sleep(5)

print("Title:", driver.title)
print("URL:", driver.current_url)

driver.quit()

Title: CGV Cinemas Vietnam | Thông tin - Lịch chiếu - Hệ thống rạp chiếu phim đẳng cấp CGV Cinemas Việt Nam
URL: https://www.cgv.vn/

In [25]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
from urllib.parse import urljoin
import time

BASE_URL = "https://www.cgv.vn/"

driver = webdriver.Chrome()

try:
    driver.get(BASE_URL)

    # Chờ trang tải
    time.sleep(5)

    # Lấy HTML sau khi Chrome tải trang
    soup = BeautifulSoup(driver.page_source, "html.parser")

    # Tìm các thẻ phim
    movies = soup.select("li.poster-film")

    print("Số lượng phim tìm thấy:", len(movies))

    data = []

    for movie in movies:

        # Hình ảnh
        img = movie.select_one("img.product-img")

        # Rating
        rating = movie.select_one(".nmovie-rating")

        # Link chi tiết
        detail_link = movie.select_one('a[title="Xem chi tiết"]')

        # Tên phim
        movie_name = img.get("alt") if img else None

        # URL hình ảnh
        image_url = img.get("src") if img else None

        # Rating
        movie_rating = (
            rating.get_text(strip=True)
            if rating else None
        )

        # URL phim
        movie_url = (
            urljoin(BASE_URL, detail_link.get("href"))
            if detail_link else None
        )

        data.append({
            "MovieName": movie_name,
            "MovieURL": movie_url,
            "ImageURL": image_url,
            "Rating": movie_rating
        })

    # Chuyển sang DataFrame
    df = pd.DataFrame(data)

    print(df.head(10))

finally:
    driver.quit()

Số lượng phim tìm thấy: 29
                                           MovieName  \
0  AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT (CHIẾU ...
1  AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT (CHIẾU ...
2                                    TRẠI BUÔN NGƯỜI
3                                  HÒN ĐẢO QUÊN LÃNG
4                                          LÊN HƯƠNG
5                                           ÚT LAN 2
6                                    VÙNG ĐẤT QUỶ DỮ
7                                     MARNIE YÊU DẤU
8                                    BÓNG MA NHÀ HÁT
9                                    TẾ NHI CẢI MỆNH

                                            MovieURL  \
0  https://www.cgv.vn/default/avengers-endgame-en...
1  https://www.cgv.vn/default/avengers-endgame-en...
2    https://www.cgv.vn/default/trai-buon-nguoi.html
3   https://www.cgv.vn/default/forgotten-island.html
4          https://www.cgv.vn/default/len-huong.html
5           https://www.cgv.vn/default/ut-lan-2.html
6  https://www.cgv.vn/default/resident-evil-2026....
7     https://www.cgv.vn/default/marnie-yeu-dau.html
8    https://www.cgv.vn/default/bong-ma-nha-hat.html
9       https://www.cgv.vn/default/tao-exorcist.html

                                            ImageURL Rating
0  https://static-cgv.vncdn.vn/media/catalog/prod...    T13
1  https://static-cgv.vncdn.vn/media/catalog/prod...    T13
2  https://static-cgv.vncdn.vn/media/catalog/prod...    T18
3  https://static-cgv.vncdn.vn/media/catalog/prod...      K
4  https://static-cgv.vncdn.vn/media/catalog/prod...    T16
5  https://static-cgv.vncdn.vn/media/catalog/prod...    T18
6  https://static-cgv.vncdn.vn/media/catalog/prod...    T18
7  https://static-cgv.vncdn.vn/media/catalog/prod...      K
8  https://static-cgv.vncdn.vn/media/catalog/prod...    T16
9  https://static-cgv.vncdn.vn/media/catalog/prod...    T18

In [24]:
print(movies[0].prettify()[:5000])

<li class="poster-film film-lists item cycle-slide active cycle-sentinel" style="position: static; top: 0px; left: 0px; z-index: 100; opacity: 1; display: block; visibility: hidden;">
 <span class="nmovie-rating nmovie-rating-t13" style="visibility: hidden;">
  T13
 </span>
 <span class="events events-sneak-show" style="visibility: hidden;">
 </span>
 <img alt="AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT (CHIẾU LẠI)" class="product-img" src="https://static-cgv.vncdn.vn/media/catalog/product/cache/1/thumbnail/240x388/c88460ec71d04fa96e628a21494d2fd3/e/n/encore_alt_1sht_-_rgb_online_only.jpg" style="visibility: hidden;"/>
 <input style="visibility: hidden;" type="hidden" value="movie-trailer-1423"/>
 <div class="feature_film_content" style="visibility: hidden;">
  <h3 style="visibility: hidden;">
   AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT (CHIẾU LẠI)
  </h3>
  <a class="button" href="https://www.cgv.vn/default/avengers-endgame-encore.html" style="visibility: hidden;" title="Xem chi tiết">
   Xem chi tiết
  </a>
  <button class="button btn-booking" onclick="Quickbooking('26022300');" style="visibility: hidden;" title="Mua vé" type="button">
   <span style="visibility: hidden;">
    <span style="visibility: hidden;">
     Mua vé
    </span>
   </span>
  </button>
 </div>
 <div class="play-button" style="visibility: hidden;">
  <span style="visibility: hidden;">
   <span style="visibility: hidden;">
    Play
   </span>
  </span>
  <div style="display: none; visibility: hidden;">
   <span class="movie-trailer" style="visibility: hidden;">
    https://www.youtube.com/embed/XsDQf4EsZIs?rel=0&amp;showinfo=0&amp;autoplay=1
   </span>
  </div>
 </div>
</li>

In [28]:
df

,MovieName,MovieURL,ImageURL,Rating
0,AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT (CHIẾU ...,https://www.cgv.vn/default/avengers-endgame-en...,https://static-cgv.vncdn.vn/media/catalog/prod...,T13
1,AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT (CHIẾU ...,https://www.cgv.vn/default/avengers-endgame-en...,https://static-cgv.vncdn.vn/media/catalog/prod...,T13
2,TRẠI BUÔN NGƯỜI,https://www.cgv.vn/default/trai-buon-nguoi.html,https://static-cgv.vncdn.vn/media/catalog/prod...,T18
3,HÒN ĐẢO QUÊN LÃNG,https://www.cgv.vn/default/forgotten-island.html,https://static-cgv.vncdn.vn/media/catalog/prod...,K
4,LÊN HƯƠNG,https://www.cgv.vn/default/len-huong.html,https://static-cgv.vncdn.vn/media/catalog/prod...,T16
5,ÚT LAN 2,https://www.cgv.vn/default/ut-lan-2.html,https://static-cgv.vncdn.vn/media/catalog/prod...,T18
6,VÙNG ĐẤT QUỶ DỮ,https://www.cgv.vn/default/resident-evil-2026....,https://static-cgv.vncdn.vn/media/catalog/prod...,T18
7,MARNIE YÊU DẤU,https://www.cgv.vn/default/marnie-yeu-dau.html,https://static-cgv.vncdn.vn/media/catalog/prod...,K
8,BÓNG MA NHÀ HÁT,https://www.cgv.vn/default/bong-ma-nha-hat.html,https://static-cgv.vncdn.vn/media/catalog/prod...,T16
9,TẾ NHI CẢI MỆNH,https://www.cgv.vn/default/tao-exorcist.html,https://static-cgv.vncdn.vn/media/catalog/prod...,T18
10,YÊU NHÂN THẦN THÁM: KỲ ÁN TRƯỜNG AN,https://www.cgv.vn/default/demon-agent.html,https://static-cgv.vncdn.vn/media/catalog/prod...,K
11,NGHỈ HÈ SỢ NGHỈ HƯU,https://www.cgv.vn/default/nghi-he-so-nghi-huu...,https://static-cgv.vncdn.vn/media/catalog/prod...,T13
12,HOPE VÙNG TỬ ĐỊA,https://www.cgv.vn/default/hope.html,https://static-cgv.vncdn.vn/media/catalog/prod...,T16
13,QUÝ TỬ VƯỢT GIÀU,https://www.cgv.vn/default/quy-tu-vuot-giau.html,https://static-cgv.vncdn.vn/media/catalog/prod...,K
14,MÃI NỢ MỘT LỜI TẠM BIỆT,https://www.cgv.vn/default/chrysalis.html,https://static-cgv.vncdn.vn/media/catalog/prod...,K
15,CỔ THUẬT HẮC NGẢI,https://www.cgv.vn/default/kong-tao.html,https://static-cgv.vncdn.vn/media/catalog/prod...,T16
16,BÙA YÊU: BÍ MẬT GIA TỘC,https://www.cgv.vn/default/bua-yeu-bi-mat-gia-...,https://static-cgv.vncdn.vn/media/catalog/prod...,T13
17,CHIIKAWA: BÍ MẬT ĐẢO NGƯỜI CÁ,https://www.cgv.vn/default/chiikawa-the-movie....,https://static-cgv.vncdn.vn/media/catalog/prod...,p
18,BÁT TIÊN ! TRUY TÌM LƯU LY ĐĂNG,https://www.cgv.vn/default/bat-tien.html,https://static-cgv.vncdn.vn/media/catalog/prod...,K
19,HỘ LINH TRÁNG SĨ - Bí Ẩn Mộ Vua Đinh (RÚT GỌN),https://www.cgv.vn/default/ho-linh-trang-si-ru...,https://static-cgv.vncdn.vn/media/catalog/prod...,T13
20,MA TÙ,https://www.cgv.vn/default/ma-tu.html,https://static-cgv.vncdn.vn/media/catalog/prod...,T18
21,MỘT ĐÊM DUY NHẤT,https://www.cgv.vn/default/one-night-only.html,https://static-cgv.vncdn.vn/media/catalog/prod...,T18
22,PHIM SHIN – CẬU BÉ BÚT CHÌ: KỲ KỲ QUÁI QUÁI! K...,https://www.cgv.vn/default/shin-yokai-vacation...,https://static-cgv.vncdn.vn/media/catalog/prod...,p
23,TÀU BUÔN NGƯỜI,https://www.cgv.vn/default/mutiny.html,https://static-cgv.vncdn.vn/media/catalog/prod...,T18
24,QUỶ QUYỆT: RANH GIỚI VÔ ĐỊNH,https://www.cgv.vn/default/insidious-further.html,https://static-cgv.vncdn.vn/media/catalog/prod...,T16
25,PAW PATROL: PHIM KHỦNG LONG,https://www.cgv.vn/default/paw-patrol-dino.html,https://static-cgv.vncdn.vn/media/catalog/prod...,p
26,NGƯỜI NHỆN: KHỞI ĐẦU MỚI,https://www.cgv.vn/default/spider-brand-new-da...,https://static-cgv.vncdn.vn/media/catalog/prod...,T13
27,THE ODYSSEY,https://www.cgv.vn/default/the-odyssey.html,https://static-cgv.vncdn.vn/media/catalog/prod...,T16
28,KHÔNG CÒN CHÚNG TA (CHIẾU LẠI),https://www.cgv.vn/default/once-we-were-us.html,https://static-cgv.vncdn.vn/media/catalog/prod...,T13

In [27]:
from selenium import webdriver
from bs4 import BeautifulSoup

driver = webdriver.Chrome()

url = "https://www.cgv.vn/default/forgotten-island.html"

try:
    driver.get(url)

    soup = BeautifulSoup(driver.page_source, "html.parser")

    # Tìm các phần tử chứa thông tin phim
    for text in ["Đạo diễn", "Diễn viên", "Thể loại", "Khởi chiếu", "Thời lượng", "Ngôn ngữ"]:
        element = soup.find(string=lambda x: x and text in x)

        print("\n====================")
        print(text)
        print("====================")

        if element:
            print(element.parent.parent.prettify()[:2000])
        else:
            print("Không tìm thấy")

finally:
    driver.quit()

====================
Đạo diễn
====================
Không tìm thấy

====================
Diễn viên
====================
Không tìm thấy

====================
Thể loại
====================
Không tìm thấy

====================
Khởi chiếu
====================
Không tìm thấy

====================
Thời lượng
====================
Không tìm thấy

====================
Ngôn ngữ
====================
Không tìm thấy

In [2]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time

driver = webdriver.Chrome()

url = "https://www.cgv.vn/default/forgotten-island.html"

try:
    driver.get(url)
    time.sleep(3)

    soup = BeautifulSoup(driver.page_source, "html.parser")

    data = {
        "MovieURL": url
    }

    # Tên phim
    title = soup.select_one("h1")

    if title:
        data["MovieName"] = title.get_text(" ", strip=True)

    # Các thông tin chi tiết
    movie_info = soup.select("div.movie-info")

    for item in movie_info:

        label = item.select_one("label")
        value = item.select_one(".std")

        if label and value:

            field = label.get_text(" ", strip=True)
            value_text = value.get_text(" ", strip=True)

            if "Đạo diễn" in field:
                data["Director"] = value_text

            elif "Diễn viên" in field:
                data["Actors"] = value_text

            elif "Thể loại" in field:
                data["Genre"] = value_text

            elif "Khởi chiếu" in field:
                data["ReleaseDate"] = value_text

            elif "Thời lượng" in field:
                data["Duration"] = value_text

            elif "Ngôn ngữ" in field:
                data["Language"] = value_text

    print(data)

finally:
    driver.quit()

{'MovieURL': 'https://www.cgv.vn/default/forgotten-island.html', 'MovieName': 'HÒN ĐẢO QUÊN LÃNG', 'Director': 'Joel Crawford; Januel Mercado', 'Actors': 'H.E.R., Liza Soberano, Dave Franco, Jenny Slate, Manny Jacinto, Dolly de Leon, Jo Koy, Ronny Chieng và Lea Salonga.', 'Genre': 'Hoạt Hình, Phiêu Lưu', 'ReleaseDate': '25/09/2026', 'Duration': '109 phút', 'Language': 'Phụ đề Tiếng Việt & Lồng Tiếng Việt'}

In [7]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time

driver = webdriver.Chrome()

results = []

try:

    # =========================
    # BƯỚC 1: LẤY DANH SÁCH PHIM
    # =========================

    driver.get("https://www.cgv.vn/")

    time.sleep(3)

    soup = BeautifulSoup(driver.page_source, "html.parser")

    # Loại cycle-sentinel để tránh phim bị lặp
    movies = soup.select(
        "li.poster-film:not(.cycle-sentinel)"
    )

    print("Số phim:", len(movies))

    movie_list = []

    for movie in movies:

        img = movie.select_one("img.product-img")

        detail_link = movie.select_one(
            'a[title="Xem chi tiết"]'
        )

        rating = movie.select_one(
            ".nmovie-rating"
        )

        if not img or not detail_link:
            continue

        movie_name = img.get("alt")

        movie_url = detail_link.get("href")

        movie_rating = (
            rating.get_text(" ", strip=True)
            if rating else None
        )

        movie_list.append({
            "MovieName": movie_name,
            "MovieURL": movie_url,
            "Rating": movie_rating
        })


    # =========================
    # BƯỚC 2: VÀO TỪNG PHIM
    # =========================

    for i, movie in enumerate(movie_list, start=1):

        print(
            f"[{i}/{len(movie_list)}] "
            f"{movie['MovieName']}"
        )

        driver.get(movie["MovieURL"])

        time.sleep(2)

        soup = BeautifulSoup(
            driver.page_source,
            "html.parser"
        )

        data = {
            "MovieName": movie["MovieName"],
            "MovieURL": movie["MovieURL"],
            "Rating": movie["Rating"],
            "Director": None,
            "Actors": None,
            "Genre": None,
            "ReleaseDate": None,
            "Duration": None,
            "Language": None
        }

        # =========================
        # LẤY THÔNG TIN movie-info
        # =========================

        movie_info = soup.select(
            "div.movie-info"
        )

        for item in movie_info:

            label = item.select_one("label")
            value = item.select_one(".std")

            if not label or not value:
                continue

            field = label.get_text(
                " ",
                strip=True
            )

            value_text = value.get_text(
                " ",
                strip=True
            )

            if "Đạo diễn" in field:
                data["Director"] = value_text

            elif "Diễn viên" in field:
                data["Actors"] = value_text

            elif "Thể loại" in field:
                data["Genre"] = value_text

            elif "Khởi chiếu" in field:
                data["ReleaseDate"] = value_text

            elif "Thời lượng" in field:
                data["Duration"] = value_text

            elif "Ngôn ngữ" in field:
                data["Language"] = value_text


        results.append(data)


finally:
    driver.quit()


# =========================
# BƯỚC 3: DATAFRAME
# =========================

df = pd.DataFrame(results)

print("\n===== KẾT QUẢ =====")

print(df.head(10))

print("\nSố dòng:", len(df))

print("\nSố cột:", len(df.columns))


# =========================
# BƯỚC 4: LƯU FILE
# =========================

df.to_csv(
    "cgv_movie_details.csv",
    index=False,
    encoding="utf-8-sig"
)

print("\nĐã lưu: cgv_movie_details.csv")

Số phim: 30
[1/30] AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT (CHIẾU LẠI)
[2/30] TRẠI BUÔN NGƯỜI
[3/30] VÙNG ĐẤT QUỶ DỮ
[4/30] HÒN ĐẢO QUÊN LÃNG
[5/30] ÚT LAN 2
[6/30] LÊN HƯƠNG
[7/30] PHÁO HOA LÚC BÌNH MINH
[8/30] LAPUTA: LÂU ĐÀI TRÊN KHÔNG
[9/30] MARNIE YÊU DẤU
[10/30] BÓNG MA NHÀ HÁT
[11/30] TẾ NHI CẢI MỆNH
[12/30] YÊU NHÂN THẦN THÁM: KỲ ÁN TRƯỜNG AN
[13/30] NGHỈ HÈ SỢ NGHỈ HƯU
[14/30] HOPE VÙNG TỬ ĐỊA
[15/30] QUÝ TỬ VƯỢT GIÀU
[16/30] MÃI NỢ MỘT LỜI TẠM BIỆT
[17/30] CỔ THUẬT HẮC NGẢI
[18/30] BÙA YÊU: BÍ MẬT GIA TỘC
[19/30] CHIIKAWA: BÍ MẬT ĐẢO NGƯỜI CÁ
[20/30] BÁT TIÊN ! TRUY TÌM LƯU LY ĐĂNG
[21/30] HỘ LINH TRÁNG SĨ - Bí Ẩn Mộ Vua Đinh (RÚT GỌN)
[22/30] MA TÙ
[23/30] MỘT ĐÊM DUY NHẤT
[24/30] PHIM SHIN – CẬU BÉ BÚT CHÌ: KỲ KỲ QUÁI QUÁI! KỲ NGHỈ YÊU QUÁI CỦA TỚ
[25/30] TÀU BUÔN NGƯỜI
[26/30] QUỶ QUYỆT: RANH GIỚI VÔ ĐỊNH
[27/30] PAW PATROL: PHIM KHỦNG LONG
[28/30] NGƯỜI NHỆN: KHỞI ĐẦU MỚI
[29/30] THE ODYSSEY
[30/30] KHÔNG CÒN CHÚNG TA (CHIẾU LẠI)

===== KẾT QUẢ =====
                                           MovieName  \
0  AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT (CHIẾU ...
1                                    TRẠI BUÔN NGƯỜI
2                                    VÙNG ĐẤT QUỶ DỮ
3                                  HÒN ĐẢO QUÊN LÃNG
4                                           ÚT LAN 2
5                                          LÊN HƯƠNG
6                             PHÁO HOA LÚC BÌNH MINH
7                         LAPUTA: LÂU ĐÀI TRÊN KHÔNG
8                                     MARNIE YÊU DẤU
9                                    BÓNG MA NHÀ HÁT

                                            MovieURL Rating  \
0  https://www.cgv.vn/default/avengers-endgame-en...    T13
1    https://www.cgv.vn/default/trai-buon-nguoi.html    T18
2  https://www.cgv.vn/default/resident-evil-2026....    T18
3   https://www.cgv.vn/default/forgotten-island.html      K
4           https://www.cgv.vn/default/ut-lan-2.html    T18
5          https://www.cgv.vn/default/len-huong.html    T16
6         https://www.cgv.vn/default/a-new-dawn.html      p
7             https://www.cgv.vn/default/laputa.html      K
8     https://www.cgv.vn/default/marnie-yeu-dau.html      K
9    https://www.cgv.vn/default/bong-ma-nha-hat.html    T16

                        Director  \
0       Anthony Russo, Joe Russo
1             Toni Dương Bảo Anh
2                   Zach Cregger
3  Joel Crawford; Januel Mercado
4                 Trần Trọng Dần
5  Khương Ngọc & Tấn Hoàng Thông
6           Yoshitoshi Shinomiya
7                 Hayao Miyazaki
8           Hiromasa Yonebayashi
9                    Lê Công Sơn

                                              Actors  \
0  Robert Downey Jr., Chris Evans, Mark Ruffalo, ...
1  Steven Nguyễn, Quách Ngọc Ngoan, Tùng Mint, Hu...
2  Austin Abrams,Paul Walter Hauser, Zach Cherry,...
3  H.E.R., Liza Soberano, Dave Franco, Jenny Slat...
4  Phương Nam, Kiều Oanh, NSUT Kim Phương, Kiều D...
5  Hồng Đào, Võ Tấn Phát, Tuyết Thu, NSND Hồng Vâ...
6         Riku Hagiwara, Kotone Furukawa, Miyu Irino
7  Mayumi Tanaka, Keiko Yokozawa, Kotoe Hatsui, M...
8  Sara Takatsuki, Kasumi Arimura, Hana Sugisaki,...
9  Trâm Anh, Quỳnh Lý, Sở Lam (Phương Lan), Hoàng...

                                       Genre ReleaseDate     Duration  \
0  Hành Động, Khoa Học Viễn Tưởng, Phiêu Lưu  25/09/2026     183 phút
1                         Hành Động, Hồi hộp  25/09/2026     135 phút
2                         Hành Động, Kinh Dị  18/09/2026      94 phút
3                       Hoạt Hình, Phiêu Lưu  25/09/2026     109 phút
4                                    Kinh Dị  25/09/2026  107 minutes
5                           Gia đình, Tâm Lý  18/09/2026     121 phút
6                                  Hoạt Hình  25/09/2026      76 phút
7                                  Hoạt Hình  25/09/2026     129 phút
8                                  Hoạt Hình  18/09/2026     103 phút
9                               Hài, Kinh Dị  18/09/2026      97 phút

                                          Language
0                  Tiếng Anh với phụ đề tiếng Việt
1                                       Tiếng Việt
2                    Tiếng Anh - Phụ đề Tiếng Việt
3              Phụ đề Tiếng Việt & Lồng Tiếng Việt
4                                       Vietnamese
5                                       Tiếng Việt
6                    Phụ đề tiếng Việt & tiếng Anh
7  Tiếng Nhật - Phụ đề Tiếng Việt; Lồng Tiếng Việt
8  Tiếng Nhật - Phụ đề Tiếng Việt; Lồng Tiếng Việt
9                                       Tiếng Việt

Số dòng: 30

Số cột: 9

Đã lưu: cgv_movie_details.csv

In [6]:
import pandas as pd

df = pd.read_csv("D:\Project_Group3\cgv_movie_details.csv")

df.head()

,MovieName,MovieURL,Rating,Director,Actors,Genre,ReleaseDate,Duration,Language
0,AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT (CHIẾU ...,https://www.cgv.vn/default/avengers-endgame-en...,T13,"Anthony Russo, Joe Russo","Robert Downey Jr., Chris Evans, Mark Ruffalo, ...","Hành Động, Khoa Học Viễn Tưởng, Phiêu Lưu",25/09/2026,183 phút,Tiếng Anh với phụ đề tiếng Việt
1,TRẠI BUÔN NGƯỜI,https://www.cgv.vn/default/trai-buon-nguoi.html,T18,Toni Dương Bảo Anh,"Steven Nguyễn, Quách Ngọc Ngoan, Tùng Mint, Hu...","Hành Động, Hồi hộp",25/09/2026,135 phút,Tiếng Việt
2,VÙNG ĐẤT QUỶ DỮ,https://www.cgv.vn/default/resident-evil-2026....,T18,Zach Cregger,"Austin Abrams,Paul Walter Hauser, Zach Cherry,...","Hành Động, Kinh Dị",18/09/2026,94 phút,Tiếng Anh - Phụ đề Tiếng Việt
3,HÒN ĐẢO QUÊN LÃNG,https://www.cgv.vn/default/forgotten-island.html,K,Joel Crawford; Januel Mercado,"H.E.R., Liza Soberano, Dave Franco, Jenny Slat...","Hoạt Hình, Phiêu Lưu",25/09/2026,109 phút,Phụ đề Tiếng Việt & Lồng Tiếng Việt
4,ÚT LAN 2,https://www.cgv.vn/default/ut-lan-2.html,T18,Trần Trọng Dần,"Phương Nam, Kiều Oanh, NSUT Kim Phương, Kiều D...",Kinh Dị,25/09/2026,107 phút,Tiếng Việt