# BƯỚC 3 – TÍCH HỢP DỮ LIỆU: CONCAT & MERGE

Notebook thực hiện:
1. Kiểm tra và chuẩn hóa `cgv_movie_details.csv` và `cgv_upcoming_movie(s).csv`.
2. Dùng `pd.concat()` để nối dọc thành **Bảng Dữ liệu Tĩnh Hợp nhất**.
3. Kiểm tra khóa `MovieName`.
4. Dùng `pd.merge()` để kết hợp bảng tĩnh với `cgv_showtimes_AI_generated.csv`.
5. Giải thích lý do chọn kiểu gộp.

Đặt 3 file CSV trong cùng thư mục với notebook.

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 80)

# Thư mục chứa các file CSV
DATA_DIR = Path.cwd()
DETAIL_FILE = DATA_DIR / "cgv_movie_details.csv"
UPCOMING_FILE = DATA_DIR / "cgv_upcoming_movies.csv"
SHOWTIMES_AI_FILE = DATA_DIR / "cgv_showtimes_AI_generated.csv"

print("DETAIL_FILE:", DETAIL_FILE)
print("UPCOMING_FILE:", UPCOMING_FILE)
print("SHOWTIMES_AI_FILE:", SHOWTIMES_AI_FILE)

print("\nKiểm tra:")
print("cgv_movie_details.csv:", DETAIL_FILE.exists())
print("cgv_upcoming_movies.csv:", UPCOMING_FILE.exists())
print("cgv_showtimes_AI_generated.csv:", SHOWTIMES_AI_FILE.exists())

DETAIL_FILE: d:\Project_Group3\cgv_movie_details.csv
UPCOMING_FILE: d:\Project_Group3\cgv_upcoming_movies.csv
SHOWTIMES_AI_FILE: d:\Project_Group3\cgv_showtimes_AI_generated.csv

Kiểm tra:
cgv_movie_details.csv: True
cgv_upcoming_movies.csv: True
cgv_showtimes_AI_generated.csv: True

In [3]:
# Đọc dữ liệu
df_details = pd.read_csv(DETAIL_FILE, encoding="utf-8-sig")
df_upcoming = pd.read_csv(UPCOMING_FILE, encoding="utf-8-sig")
df_showtimes_ai = pd.read_csv(SHOWTIMES_AI_FILE, encoding="utf-8-sig")

print("cgv_movie_details:", df_details.shape)
print("cgv_upcoming_movies:", df_upcoming.shape)
print("cgv_showtimes_AI:", df_showtimes_ai.shape)

display(df_details.head())
display(df_upcoming.head())
display(df_showtimes_ai.head())

cgv_movie_details: (30, 9)
cgv_upcoming_movies: (34, 9)
cgv_showtimes_AI: (1172, 6)

,MovieName,MovieURL,Rating,Director,Actors,Genre,ReleaseDate,Duration,Language
0,AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT (CHIẾU LẠI),https://www.cgv.vn/default/avengers-endgame-encore.html,T13,"Anthony Russo, Joe Russo","Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Joha...","Hành Động, Khoa Học Viễn Tưởng, Phiêu Lưu",25/09/2026,183 phút,Tiếng Anh với phụ đề tiếng Việt
1,TRẠI BUÔN NGƯỜI,https://www.cgv.vn/default/trai-buon-nguoi.html,T18,Toni Dương Bảo Anh,"Steven Nguyễn, Quách Ngọc Ngoan, Tùng Mint, Huỳnh Minh Kiên,...","Hành Động, Hồi hộp",25/09/2026,135 phút,Tiếng Việt
2,VÙNG ĐẤT QUỶ DỮ,https://www.cgv.vn/default/resident-evil-2026.html,T18,Zach Cregger,"Austin Abrams,Paul Walter Hauser, Zach Cherry, Kali Reis.","Hành Động, Kinh Dị",18/09/2026,94 phút,Tiếng Anh - Phụ đề Tiếng Việt
3,HÒN ĐẢO QUÊN LÃNG,https://www.cgv.vn/default/forgotten-island.html,K,Joel Crawford; Januel Mercado,"H.E.R., Liza Soberano, Dave Franco, Jenny Slate, Manny Jacinto, Dolly de Leo...","Hoạt Hình, Phiêu Lưu",25/09/2026,109 phút,Phụ đề Tiếng Việt & Lồng Tiếng Việt
4,ÚT LAN 2,https://www.cgv.vn/default/ut-lan-2.html,T18,Trần Trọng Dần,"Phương Nam, Kiều Oanh, NSUT Kim Phương, Kiều Diễm, Gia Tuệ, Tạ Lâm, Ngọc Phư...",Kinh Dị,25/09/2026,107 minutes,Vietnamese

,MovieName,MovieURL,Rating,Director,Actors,Genre,ReleaseDate,Duration,Language
0,TRÁI TIM QUÁI THÚ,https://www.cgv.vn/default/heart-of-the-beast.html,T13,David Ayer,"Brad Pitt, J.K. Simmons, Anna Lambe",Hành Động,02/10/2026,101 phút,Tiếng Anh - Phụ đề Tiếng Việt
1,THẦN SƯ CHUNG QUỲ: LINH GIỚI ĐẠI CHIẾN,https://www.cgv.vn/default/master-zhong.html,NaN,Wang Yuxi and Huang Shanchuan,"Duan Yixuan, Yu Haowei, Hu Liangwei, Zhao Chengchen, Ba He, and Hu Zhengjian.","Hành Động, Hoạt Hình, Phiêu Lưu, Thần thoại",02/10/2026,96 phút,Tiếng Trung Quốc - Phụ đề Tiếng Việt
2,KHÓA CHẶT CỬA NÀO SUZUME,https://www.cgv.vn/default/suzume.html,P,Makoto Shinkai,NaN,"Hoạt Hình, Phiêu Lưu",02/10/2026,122 phút,"Tiếng Nhật - Phụ đề Tiếng Việt, tiếng Anh"
3,QUYẾT CUA ANH NÀY,https://www.cgv.vn/default/quyet-cua-anh-nay.html,NaN,Mez Tharatorn,"Nadech Kugimiya, Minnie Nicha, Pa Kiat Kitcharoen, Ble Patumrach, Vivian Thi...","Hài, Tình cảm",02/10/2026,NaN,Tiếng Thái - Phụ đề tiếng Việt
4,ÁN MẠNG KARAOKE,https://www.cgv.vn/default/an-mang-karaoke.html,T16,Hoàng Lê,"Đoàn Thiên Ân, Đại Nghĩa, Vân Dung,...","Hài, Hồi hộp",02/10/2026,96 phút,Tiếng Việt

,MovieName,Cinema,ShowDate,Format,ShowTime,GeneratedText
0,AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT (CHIẾU LẠI),CGV Crescent Mall,01/10/2026,2D Phụ Đề Việt | Rạp Lamour,10:30,Tôi đã có cơ hội xem suất chiếu AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT tại r...
1,AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT (CHIẾU LẠI),CGV Crescent Mall,01/10/2026,2D Phụ Đề Việt | Rạp Lamour,16:00,"Hôm nay, tôi có cơ hội tham gia vào một trải nghiệm thú vị khi xem suất chiế..."
2,AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT (CHIẾU LẠI),CGV Crescent Mall,01/10/2026,2D Phụ Đề Việt | Rạp Lamour,21:30,Tôi đã có cơ hội xem suất chiếu AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT tại r...
3,CHIIKAWA: BÍ MẬT ĐẢO NGƯỜI CÁ,CGV Crescent Mall,01/10/2026,2D Phụ Đề Anh & Việt,18:00,"Hôm nay, tôi đã có cơ hội đến rạp chiếu CGV Crescent Mall để xem phim CHIIKA..."
4,HÒN ĐẢO QUÊN LÃNG,CGV Crescent Mall,01/10/2026,2D Lồng Tiếng Việt,19:40,"Tôi vừa có cơ hội xem suất chiếu ""HÒN ĐẢO QUÊN LÃNG"" tại rạp chiếu CGV Cresc..."

## 1. Kiểm tra cấu trúc hai bảng tĩnh

Hai bảng phải có cùng ý nghĩa bản ghi và cùng bộ cột trước khi `pd.concat()`.

Schema mục tiêu:

`MovieName, MovieURL, Rating, Director, Actors, Genre, ReleaseDate, Duration, Language`

In [4]:
def normalize_column_names(df):
    df = df.copy()
    df.columns = (
        df.columns.astype(str)
        .str.strip()
        .str.replace(r"\s+", "", regex=True)
    )
    return df

df_details = normalize_column_names(df_details)
df_upcoming = normalize_column_names(df_upcoming)
df_showtimes_ai = normalize_column_names(df_showtimes_ai)

print("Cột DETAILS :", df_details.columns.tolist())
print("Cột UPCOMING:", df_upcoming.columns.tolist())
print("Cột SHOWTIMES AI:", df_showtimes_ai.columns.tolist())

detail_cols = set(df_details.columns)
upcoming_cols = set(df_upcoming.columns)

print("\nCột có ở DETAILS nhưng thiếu ở UPCOMING:", detail_cols - upcoming_cols)
print("Cột có ở UPCOMING nhưng thiếu ở DETAILS:", upcoming_cols - detail_cols)

Cột DETAILS : ['MovieName', 'MovieURL', 'Rating', 'Director', 'Actors', 'Genre', 'ReleaseDate', 'Duration', 'Language']
Cột UPCOMING: ['MovieName', 'MovieURL', 'Rating', 'Director', 'Actors', 'Genre', 'ReleaseDate', 'Duration', 'Language']
Cột SHOWTIMES AI: ['MovieName', 'Cinema', 'ShowDate', 'Format', 'ShowTime', 'GeneratedText']

Cột có ở DETAILS nhưng thiếu ở UPCOMING: set()
Cột có ở UPCOMING nhưng thiếu ở DETAILS: set()

## 2. Chuẩn hóa dữ liệu trước `concat()`

Thực hiện:
- Chuẩn hóa tên cột.
- Xóa khoảng trắng thừa ở dữ liệu text.
- Chuẩn hóa `MovieName` để làm khóa.
- Chuyển `ReleaseDate` về kiểu ngày.
- Bổ sung cột còn thiếu.
- Đưa hai bảng về cùng schema.
- Loại bỏ dòng trùng hoàn toàn.

In [5]:
STATIC_COLUMNS = [
    "MovieName", "MovieURL", "Rating", "Director", "Actors",
    "Genre", "ReleaseDate", "Duration", "Language"
]

# Bổ sung cột thiếu
for col in STATIC_COLUMNS:
    if col not in df_details.columns:
        df_details[col] = pd.NA
    if col not in df_upcoming.columns:
        df_upcoming[col] = pd.NA

# Cùng thứ tự cột
df_details = df_details[STATIC_COLUMNS].copy()
df_upcoming = df_upcoming[STATIC_COLUMNS].copy()

TEXT_COLS = [
    "MovieName", "MovieURL", "Rating", "Director",
    "Actors", "Genre", "Duration", "Language"
]

def clean_text_columns(df):
    df = df.copy()
    for col in TEXT_COLS:
        df[col] = (
            df[col].fillna("")
            .astype(str)
            .str.replace(r"\s+", " ", regex=True)
            .str.strip()
        )
        df[col] = df[col].replace({"": pd.NA})
    return df

df_details = clean_text_columns(df_details)
df_upcoming = clean_text_columns(df_upcoming)

# Chuẩn hóa khóa MovieName
for df in [df_details, df_upcoming]:
    df["MovieName"] = (
        df["MovieName"].astype("string")
        .str.replace(r"\s+", " ", regex=True)
        .str.strip()
    )

# Chuẩn hóa ngày
df_details["ReleaseDate"] = pd.to_datetime(df_details["ReleaseDate"], dayfirst=True, errors="coerce")
df_upcoming["ReleaseDate"] = pd.to_datetime(df_upcoming["ReleaseDate"], dayfirst=True, errors="coerce")

print("Schema DETAILS:")
display(df_details.dtypes)

print("Schema UPCOMING:")
display(df_upcoming.dtypes)

Schema DETAILS:

MovieName      string[python]
MovieURL               object
Rating                 object
Director               object
Actors                 object
Genre                  object
ReleaseDate    datetime64[ns]
Duration               object
Language               object
dtype: object

Schema UPCOMING:

MovieName      string[python]
MovieURL               object
Rating                 object
Director               object
Actors                 object
Genre                  object
ReleaseDate    datetime64[ns]
Duration               object
Language               object
dtype: object

In [6]:
def quality_report(df, name):
    print(f"===== {name} =====")
    print("Số dòng:", len(df))
    print("Số cột:", len(df.columns))
    print("\nMissing:")
    display(df.isna().sum().to_frame("Missing"))
    print("Dòng trùng hoàn toàn:", df.duplicated().sum())
    print("MovieName trùng:", df["MovieName"].duplicated().sum())
    print()

quality_report(df_details, "CGV MOVIE DETAILS")
quality_report(df_upcoming, "CGV UPCOMING MOVIES")

overlap = (
    set(df_details["MovieName"].dropna())
    & set(df_upcoming["MovieName"].dropna())
)

print("Số MovieName xuất hiện ở cả hai nguồn:", len(overlap))
print(list(sorted(overlap))[:20])

===== CGV MOVIE DETAILS =====
Số dòng: 30
Số cột: 9

Missing:

             Missing
MovieName          0
MovieURL           0
Rating             0
Director           0
Actors             1
Genre              0
ReleaseDate        0
Duration           0
Language           0

Dòng trùng hoàn toàn: 0
MovieName trùng: 0

===== CGV UPCOMING MOVIES =====
Số dòng: 34
Số cột: 9

Missing:

             Missing
MovieName          0
MovieURL           0
Rating            31
Director           0
Actors             4
Genre              0
ReleaseDate        4
Duration          25
Language           0

Dòng trùng hoàn toàn: 0
MovieName trùng: 0

Số MovieName xuất hiện ở cả hai nguồn: 0
[]

## 3. `pd.concat()` – nối dọc

Sau khi hai bảng đã có cùng schema, dùng `pd.concat(axis=0)` để đặt các dòng của phim sắp chiếu xuống dưới các dòng phim chi tiết.

Kết quả là **Bảng Dữ liệu Tĩnh Hợp nhất**.

In [7]:
df_details_clean = df_details.drop_duplicates().copy()
df_upcoming_clean = df_upcoming.drop_duplicates().copy()

df_static_master = pd.concat(
    [df_details_clean, df_upcoming_clean],
    axis=0,
    ignore_index=True
)

print("===== BẢNG DỮ LIỆU TĨNH HỢP NHẤT =====")
print("Kích thước:", df_static_master.shape)
display(df_static_master.head())
display(df_static_master.tail())

===== BẢNG DỮ LIỆU TĨNH HỢP NHẤT =====
Kích thước: (64, 9)

,MovieName,MovieURL,Rating,Director,Actors,Genre,ReleaseDate,Duration,Language
0,AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT (CHIẾU LẠI),https://www.cgv.vn/default/avengers-endgame-encore.html,T13,"Anthony Russo, Joe Russo","Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Joha...","Hành Động, Khoa Học Viễn Tưởng, Phiêu Lưu",2026-09-25,183 phút,Tiếng Anh với phụ đề tiếng Việt
1,TRẠI BUÔN NGƯỜI,https://www.cgv.vn/default/trai-buon-nguoi.html,T18,Toni Dương Bảo Anh,"Steven Nguyễn, Quách Ngọc Ngoan, Tùng Mint, Huỳnh Minh Kiên,...","Hành Động, Hồi hộp",2026-09-25,135 phút,Tiếng Việt
2,VÙNG ĐẤT QUỶ DỮ,https://www.cgv.vn/default/resident-evil-2026.html,T18,Zach Cregger,"Austin Abrams,Paul Walter Hauser, Zach Cherry, Kali Reis.","Hành Động, Kinh Dị",2026-09-18,94 phút,Tiếng Anh - Phụ đề Tiếng Việt
3,HÒN ĐẢO QUÊN LÃNG,https://www.cgv.vn/default/forgotten-island.html,K,Joel Crawford; Januel Mercado,"H.E.R., Liza Soberano, Dave Franco, Jenny Slate, Manny Jacinto, Dolly de Leo...","Hoạt Hình, Phiêu Lưu",2026-09-25,109 phút,Phụ đề Tiếng Việt & Lồng Tiếng Việt
4,ÚT LAN 2,https://www.cgv.vn/default/ut-lan-2.html,T18,Trần Trọng Dần,"Phương Nam, Kiều Oanh, NSUT Kim Phương, Kiều Diễm, Gia Tuệ, Tạ Lâm, Ngọc Phư...",Kinh Dị,2026-09-25,107 minutes,Vietnamese

,MovieName,MovieURL,Rating,Director,Actors,Genre,ReleaseDate,Duration,Language
59,LOẠN THẾ,https://www.cgv.vn/default/loan-the.html,<NA>,Dương Minh Chiến,<NA>,Hành Động,2027-02-06,<NA>,Tiếng Việt - Phụ đề Tiếng Anh
60,ÁC TƯỢNG,https://www.cgv.vn/default/wooden-buddha.html,<NA>,"Preecha Sakorn, Niyom Wongpongkam","Mookda Narinrak, Pon Nawasch Phupantachsee, Teerapong Liaorakwong",Kinh Dị,NaT,84 phút,Tiếng Thái - Phụ đề Tiếng Việt
61,QUỶ DẮT TAY,https://www.cgv.vn/default/quy-dat-tay.html,<NA>,Alex WANG,"Vera YEN, Charles TU, Johnny KOU","Hồi hộp, Kịch tính, Kinh Dị",NaT,111 phút,Tiếng Trung - Phụ đề tiếng Việt
62,CHIẾN BÀO,https://www.cgv.vn/default/chien-bao.html,<NA>,Victor Vũ,<NA>,Lịch Sử,NaT,<NA>,Tiếng Việt
63,CỘNG TRỪ NHÂN CHIA,https://www.cgv.vn/default/cong-tru-nhan-chia.html,<NA>,IRVING LY,"Anh Thư, Lâm Thanh Mỹ, Phương Trà My, Minh Hưng, Đắc Thắng, Chu Anh Tuấn, NS...","Hồi hộp, Tâm Lý",NaT,<NA>,Tiếng Việt

In [8]:
# Kiểm tra khóa sau concat
duplicate_movies = (
    df_static_master[
        df_static_master["MovieName"].duplicated(keep=False)
    ]
    .sort_values("MovieName")
)

print("Số dòng thuộc MovieName bị trùng:", len(duplicate_movies))

if len(duplicate_movies) > 0:
    display(duplicate_movies.head(20))
    print(
        "Nếu cùng MovieName có nhiều bản ghi, merge theo MovieName "
        "có thể làm nhân bản suất chiếu. Vì vậy sẽ tạo bảng khóa duy nhất "
        "trước khi merge."
    )

Số dòng thuộc MovieName bị trùng: 0

## 4. Chuẩn hóa dữ liệu động

`cgv_showtimes_AI_generated.csv` là dữ liệu động, gồm lịch chiếu và dữ liệu văn bản do AI tạo sinh.

Khóa kết nối với bảng tĩnh là `MovieName`.

In [9]:
if "MovieName" not in df_showtimes_ai.columns:
    raise KeyError(
        "cgv_showtimes_AI_generated.csv phải có cột MovieName để merge."
    )

df_showtimes_ai["MovieName"] = (
    df_showtimes_ai["MovieName"].astype("string")
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

if "ShowDate" in df_showtimes_ai.columns:
    df_showtimes_ai["ShowDate"] = pd.to_datetime(
        df_showtimes_ai["ShowDate"], dayfirst=True, errors="coerce"
    )

print("Số dòng dữ liệu động:", len(df_showtimes_ai))
display(df_showtimes_ai.head())

Số dòng dữ liệu động: 1172

,MovieName,Cinema,ShowDate,Format,ShowTime,GeneratedText
0,AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT (CHIẾU LẠI),CGV Crescent Mall,2026-10-01,2D Phụ Đề Việt | Rạp Lamour,10:30,Tôi đã có cơ hội xem suất chiếu AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT tại r...
1,AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT (CHIẾU LẠI),CGV Crescent Mall,2026-10-01,2D Phụ Đề Việt | Rạp Lamour,16:00,"Hôm nay, tôi có cơ hội tham gia vào một trải nghiệm thú vị khi xem suất chiế..."
2,AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT (CHIẾU LẠI),CGV Crescent Mall,2026-10-01,2D Phụ Đề Việt | Rạp Lamour,21:30,Tôi đã có cơ hội xem suất chiếu AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT tại r...
3,CHIIKAWA: BÍ MẬT ĐẢO NGƯỜI CÁ,CGV Crescent Mall,2026-10-01,2D Phụ Đề Anh & Việt,18:00,"Hôm nay, tôi đã có cơ hội đến rạp chiếu CGV Crescent Mall để xem phim CHIIKA..."
4,HÒN ĐẢO QUÊN LÃNG,CGV Crescent Mall,2026-10-01,2D Lồng Tiếng Việt,19:40,"Tôi vừa có cơ hội xem suất chiếu ""HÒN ĐẢO QUÊN LÃNG"" tại rạp chiếu CGV Cresc..."

## 5. Chuẩn bị bảng tĩnh cho `merge()`

Ta tạo một bảng tra cứu trong đó mỗi `MovieName` xuất hiện một lần.

Việc này giúp tránh trường hợp một suất chiếu bị nhân thành nhiều dòng do khóa `MovieName` bị trùng ở bảng tĩnh.

In [10]:
df_static_master_unique = (
    df_static_master
    .drop_duplicates(subset=["MovieName"], keep="first")
    .copy()
)

print("Số dòng bảng tĩnh trước xử lý khóa:",
      len(df_static_master))
print("Số dòng bảng tĩnh sau xử lý khóa:",
      len(df_static_master_unique))
print("Số MovieName duy nhất:",
      df_static_master_unique["MovieName"].nunique())

static_keys = set(df_static_master_unique["MovieName"].dropna())
dynamic_keys = set(df_showtimes_ai["MovieName"].dropna())

not_found = sorted(dynamic_keys - static_keys)

print("\nMovieName trong dữ liệu động nhưng không có ở bảng tĩnh:",
      len(not_found))
if not_found:
    print(not_found[:20])

Số dòng bảng tĩnh trước xử lý khóa: 64
Số dòng bảng tĩnh sau xử lý khóa: 64
Số MovieName duy nhất: 64

MovieName trong dữ liệu động nhưng không có ở bảng tĩnh: 0

## 6. `pd.merge()` – gộp ngang

### Kiểu gộp: `LEFT JOIN`

Ta dùng:

```python
pd.merge(
    df_showtimes_ai,
    df_static_master_unique,
    on="MovieName",
    how="left"
)
```

**Lý do chọn `LEFT JOIN`:**

- Dữ liệu động `cgv_showtimes_AI_generated` là bảng chính.
- Cần giữ lại **toàn bộ suất chiếu**.
- Khi `MovieName` khớp, bổ sung thông tin phim từ bảng tĩnh.
- Nếu không khớp, suất chiếu vẫn được giữ và các cột tĩnh có thể là `NaN`.

Không chọn `INNER JOIN` vì các suất chiếu không khớp sẽ bị loại bỏ.

Không chọn `RIGHT JOIN` vì mục tiêu không phải giữ toàn bộ bảng tĩnh.

Không chọn `OUTER JOIN` vì có thể tạo thêm các phim không có suất chiếu trong bảng kết quả.

Vì vậy `LEFT JOIN` phù hợp với mục tiêu: **lấy lịch chiếu làm dữ liệu chính và bổ sung thông tin phim**.

In [11]:
df_final = pd.merge(
    df_showtimes_ai,
    df_static_master_unique,
    on="MovieName",
    how="left",
    suffixes=("", "_Static"),
    indicator=True
)

print("===== KẾT QUẢ MERGE =====")
print("Kích thước:", df_final.shape)
display(df_final.head(10))

print("\nTình trạng ghép:")
display(df_final["_merge"].value_counts())

===== KẾT QUẢ MERGE =====
Kích thước: (1172, 15)

,MovieName,Cinema,ShowDate,Format,ShowTime,GeneratedText,MovieURL,Rating,Director,Actors,Genre,ReleaseDate,Duration,Language,_merge
0,AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT (CHIẾU LẠI),CGV Crescent Mall,2026-10-01,2D Phụ Đề Việt | Rạp Lamour,10:30,Tôi đã có cơ hội xem suất chiếu AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT tại r...,https://www.cgv.vn/default/avengers-endgame-encore.html,T13,"Anthony Russo, Joe Russo","Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Joha...","Hành Động, Khoa Học Viễn Tưởng, Phiêu Lưu",2026-09-25,183 phút,Tiếng Anh với phụ đề tiếng Việt,both
1,AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT (CHIẾU LẠI),CGV Crescent Mall,2026-10-01,2D Phụ Đề Việt | Rạp Lamour,16:00,"Hôm nay, tôi có cơ hội tham gia vào một trải nghiệm thú vị khi xem suất chiế...",https://www.cgv.vn/default/avengers-endgame-encore.html,T13,"Anthony Russo, Joe Russo","Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Joha...","Hành Động, Khoa Học Viễn Tưởng, Phiêu Lưu",2026-09-25,183 phút,Tiếng Anh với phụ đề tiếng Việt,both
2,AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT (CHIẾU LẠI),CGV Crescent Mall,2026-10-01,2D Phụ Đề Việt | Rạp Lamour,21:30,Tôi đã có cơ hội xem suất chiếu AVENGERS: HỒI KẾT - PHIÊN BẢN ĐẶC BIỆT tại r...,https://www.cgv.vn/default/avengers-endgame-encore.html,T13,"Anthony Russo, Joe Russo","Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Joha...","Hành Động, Khoa Học Viễn Tưởng, Phiêu Lưu",2026-09-25,183 phút,Tiếng Anh với phụ đề tiếng Việt,both
3,CHIIKAWA: BÍ MẬT ĐẢO NGƯỜI CÁ,CGV Crescent Mall,2026-10-01,2D Phụ Đề Anh & Việt,18:00,"Hôm nay, tôi đã có cơ hội đến rạp chiếu CGV Crescent Mall để xem phim CHIIKA...",https://www.cgv.vn/default/chiikawa-the-movie.html,p,Kei Oikawa,"Haruka Aoki, Makoto Tanaka, Ari Ozawa, Yuka Iguchi, Takayuki Asai, Yuma Uchi...",Hoạt Hình,2026-08-28,99 phút,Tiếng Nhật với phụ đề Việt & Anh; Lồng tiếng Việt,both
4,HÒN ĐẢO QUÊN LÃNG,CGV Crescent Mall,2026-10-01,2D Lồng Tiếng Việt,19:40,"Tôi vừa có cơ hội xem suất chiếu ""HÒN ĐẢO QUÊN LÃNG"" tại rạp chiếu CGV Cresc...",https://www.cgv.vn/default/forgotten-island.html,K,Joel Crawford; Januel Mercado,"H.E.R., Liza Soberano, Dave Franco, Jenny Slate, Manny Jacinto, Dolly de Leo...","Hoạt Hình, Phiêu Lưu",2026-09-25,109 phút,Phụ đề Tiếng Việt & Lồng Tiếng Việt,both
5,LAPUTA: LÂU ĐÀI TRÊN KHÔNG,CGV Crescent Mall,2026-10-01,2D Lồng Tiếng Việt,12:50,"Hôm nay, tôi đã có cơ hội xem suất chiếu LAPUTA: LÂU ĐÀI TRÊN KHÔNG tại rạp ...",https://www.cgv.vn/default/laputa.html,K,Hayao Miyazaki,"Mayumi Tanaka, Keiko Yokozawa, Kotoe Hatsui, Minori Terada, Ichiro Nagai,...",Hoạt Hình,2026-09-25,129 phút,Tiếng Nhật - Phụ đề Tiếng Việt; Lồng Tiếng Việt,both
6,LAPUTA: LÂU ĐÀI TRÊN KHÔNG,CGV Crescent Mall,2026-10-01,2D Phụ Đề Việt,14:40,"Hôm nay, tôi đã có cơ hội xem suất chiếu LAPUTA: LÂU ĐÀI TRÊN KHÔNG tại rạp ...",https://www.cgv.vn/default/laputa.html,K,Hayao Miyazaki,"Mayumi Tanaka, Keiko Yokozawa, Kotoe Hatsui, Minori Terada, Ichiro Nagai,...",Hoạt Hình,2026-09-25,129 phút,Tiếng Nhật - Phụ đề Tiếng Việt; Lồng Tiếng Việt,both
7,LAPUTA: LÂU ĐÀI TRÊN KHÔNG,CGV Crescent Mall,2026-10-01,2D Lồng Tiếng Việt,17:10,Tôi vừa có cơ hội xem suất chiếu LAPUTA: LÂU ĐÀI TRÊN KHÔNG tại rạp chiếu CG...,https://www.cgv.vn/default/laputa.html,K,Hayao Miyazaki,"Mayumi Tanaka, Keiko Yokozawa, Kotoe Hatsui, Minori Terada, Ichiro Nagai,...",Hoạt Hình,2026-09-25,129 phút,Tiếng Nhật - Phụ đề Tiếng Việt; Lồng Tiếng Việt,both
8,LÊN HƯƠNG,CGV Crescent Mall,2026-10-01,2D Phụ Đề Anh,09:35,Tôi đã trải nghiệm một buổi chiếu phim tuyệt vời tại rạp CGV Crescent Mall v...,https://www.cgv.vn/default/len-huong.html,T16,Khương Ngọc & Tấn Hoàng Thông,"Hồng Đào, Võ Tấn Phát, Tuyết Thu, NSND Hồng Vân, Hạ Anh, Quốc Khánh, Thiếu Lan","Gia đình, Tâm Lý",2026-09-18,121 phút,Tiếng Việt,both
9,LÊN HƯƠNG,CGV Crescent Mall,2026-10-01,2D Phụ Đề Anh,10:20,"Tôi đã có cơ hội trải nghiệm suất chiếu ""LÊN HƯƠNG"" tại rạp chiếu CGV Cresce...",https://www.cgv.vn/default/len-huong.html,T16,Khương Ngọc & Tấn Hoàng Thông,"Hồng Đào, Võ Tấn Phát, Tuyết Thu, NSND Hồng Vân, Hạ Anh, Quốc Khánh, Thiếu Lan","Gia đình, Tâm Lý",2026-09-18,121 phút,Tiếng Việt,both

Tình trạng ghép:

_merge
both          1172
left_only        0
right_only       0
Name: count, dtype: int64

In [12]:
# Kiểm tra các dòng chưa tìm thấy thông tin tĩnh
unmatched = (
    df_final.loc[df_final["_merge"] == "left_only", ["MovieName"]]
    .drop_duplicates()
)

print("Số MovieName chưa ghép được:", len(unmatched))
display(unmatched.head(20))

# Kiểm tra missing ở các cột thông tin tĩnh
static_info_cols = [
    c for c in [
        "MovieURL", "Rating", "Director", "Actors",
        "Genre", "ReleaseDate", "Duration", "Language"
    ] if c in df_final.columns
]

print("Missing sau merge:")
display(df_final[static_info_cols].isna().sum().to_frame("Missing"))

Số MovieName chưa ghép được: 0

Empty DataFrame
Columns: [MovieName]
Index: []

Missing sau merge:

             Missing
MovieURL           0
Rating             0
Director           0
Actors             0
Genre              0
ReleaseDate        0
Duration           0
Language           0

## 7. Lưu kết quả

- `cgv_static_master.csv`: Bảng Dữ liệu Tĩnh Hợp nhất sau `concat`.
- `cgv_final_integrated.csv`: Bảng cuối sau `merge`, gồm dữ liệu lịch chiếu + AI + thông tin phim.

In [13]:
static_output = DATA_DIR / "cgv_static_master.csv"
final_output = DATA_DIR / "cgv_final_integrated.csv"

df_static_master.to_csv(
    static_output,
    index=False,
    encoding="utf-8-sig"
)

df_final_export = df_final.drop(columns=["_merge"])

df_final_export.to_csv(
    final_output,
    index=False,
    encoding="utf-8-sig"
)

print("Đã lưu:")
print("-", static_output)
print("-", final_output)

Đã lưu:
- d:\Project_Group3\cgv_static_master.csv
- d:\Project_Group3\cgv_final_integrated.csv

# KẾT LUẬN

**Nối dọc (`CONCAT`):**

`cgv_movie_details.csv` + `cgv_upcoming_movie(s).csv`
→ kiểm tra → chuẩn hóa → `pd.concat()`
→ **Bảng Dữ liệu Tĩnh Hợp nhất**

**Gộp ngang (`MERGE`):**

`cgv_showtimes_AI_generated.csv` + Bảng Dữ liệu Tĩnh Hợp nhất
→ khóa chung `MovieName`
→ **LEFT JOIN**
→ **Bảng dữ liệu tích hợp cuối cùng**

`LEFT JOIN` được chọn vì cần bảo toàn toàn bộ các suất chiếu của bảng động, sau đó mới bổ sung thông tin phim từ bảng tĩnh.